title: Mousehunt Guide

exclude: [
  ".github/",
  ".devcontainer/",
  ".vscode/",
  "node_modules/",
  ".gitignore",
  ".prettierignore",
  ".prettierrc",
  ".stylelintrc.json",
  "CONTRIBUTING.md",
  "docker-compose.yml",
  "Dockerfile",
  "Gemfile",
  "Gemfile.lock",
  "guide.gemspec",
  "LICENSE.md",
  "package.json",
  "package-lock.json",
  "Rakefile",
  "README.md",
  "Template.md"
]

collections:
  pages:
    output: true
    permalink: /:title/
  ranks:
    output: true
    permalink: /:title/

aux_links:
  "mouse.rip":
    - "https://mouse.rip"
  "Discord":
    - "https://discordapp.com/mousehunt"


just_the_docs:
  collections:
    ranks:
      name: Guides for Ranks
      nav_fold: false
      nav_order: 1
    pages:
      name: Other Links
      nav_fold: true
      nav_order: 2

search_enabled: true
search:
  heading_level: 3
  previews: 5
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

aux_links_new_tab: true
heading_anchors: true
back_to_top: true
back_to_top_text: "back to top"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
