version: "3.5"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    environment:
      JEKYLL_ENV: docker
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --host=0.0.0.0 -t --config _config.yml,_config.docker.yml

